# Generated by Django 4.1.1 on 2023-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accesstokenoutstand'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokenoutstand',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
    ]
